config/routes.rb
Rails.application.routes.draw do
  get 'about/acknowledgements', to: 'static_pages#acknowledgements'
  use_doorkeeper

  # Static pages
  root to: "pages#home"
  get '/home' => 'pages#home'
  get '/database' => 'pages#database'
  get '/api' => 'pages#api'

  # Articles (news posts and other pseudo-static pages)
  get '/news', to: 'articles#index', section: 'news'
  get 'news/:slug', to: 'articles#show'
  get 'about/:slug', to: 'articles#show'
  get 'docs/:slug', to: 'articles#show'

  # Redirects for backwards compatibility
  get '/about', to: redirect('/about/xronos')

  # Primary data resources
  resources :c14s do
    get 'search', on: :collection
    member do
      get 'calibrate'
      get 'calibrate_multi'
      get 'calibrate_sum'
    end
  end
  resources :c14_labs
  resources :contexts
  resources :duplicates
  resources :materials do
    get 'search', on: :collection
  end
  resources :measurement_states
  resources :references do
    get 'search', on: :collection
  end
  resources :sites do
    get 'search', on: :collection
    resources :site_names, except: [:index, :show]
  end
  resources :site_types do
    get 'search', on: :collection
  end
  resources :typos do
    get 'search', on: :collection
  end

  # Secondary data resources (no independent show/index views)
  resources :taxons, except: [:index, :show] do
    get 'search', on: :collection
  end
  resources :taxon_usages, only: :show

  # External data resources
  resources :lod_links, except: :index

  # User management
  devise_for :users, controllers: {
      registrations: 'registrations',
      sessions: 'users/sessions'
    }
  resources :user_profiles, except: [:index, :show] do
    resource :photo, only: [ :destroy ], controller: "user_profiles/photo"
  end
  resources :contributors, controller: :user_profiles, only: [ :show ]

  # Admin interface
  get "/admin" => "admin#index"
  namespace :admin do
    resources :articles, except: :show
    resources :users
  end

  # Data browser
  get 'data/index'
  post 'data/index'
  get "/data" => "xronos_data#index"

  # Search
  get "search" => "searches#index"

  # Data filter controls
  get '/resetfilter', to: 'xronos_data#reset_filter_session_variable'
  get '/turn_off_lasso', to: 'xronos_data#turn_off_lasso'
  get '/reset_manual_table_selection', to: 'xronos_data#reset_manual_table_selection'

  # Curation backend
  get "/curate" => "curate#index"
  namespace :curate do
    resources :import_tables do
      get 'edit' => 'import_tables#edit_read_options'
      get 'edit/read_options' => 'import_tables#edit_read_options'
      get 'edit/mapping' => 'import_tables#edit_mapping'
    end
    get "recent_changes" => "recent_changes#index"
  end

  # Data issues
  namespace :issues do 
    resources :c14s, only: :index do
      collection do
        get ":issue", action: :index,
          constraints: lambda { |req| C14.issues.include?(req.params[:issue].to_sym) }
      end
    end
    resources :references, only: :index do
      collection do
        get ":issue", action: :index,
          constraints: lambda { |req| Reference.issues.include?(req.params[:issue].to_sym) }
      end
    end
    resources :samples, only: :index do
      collection do
        get ":issue", action: :index,
          constraints: lambda { |req| Sample.issues.include?(req.params[:issue].to_sym) }
      end
    end
    resources :sites, only: :index do
      collection do
        get ":issue", action: :index,
          constraints: lambda { |req| Site.issues.include?(req.params[:issue].to_sym) }
      end
    end
    resources :taxons, only: :index do
      collection do
        get ":issue", action: :index,
          constraints: lambda { |req| Taxon.issues.include?(req.params[:issue].to_sym) }
      end
    end
  end
  
  # LODs
  namespace :lods do
    resources :sites, only: :index do
      collection do
        get ":lod", action: :index,
          constraints: lambda { |req| Site.lods.include?(req.params[:lod].to_sym) }
      end
    end
  end

  # API
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :data, controller: 'xronos_data'
    end
  end
  
end

app/controllers/duplicates_controller.rb
class DuplicatesController < ApplicationController
  include Pagy::Backend

  def index
    @sites = Site.all_duplicated
    @pagy, @sites = pagy(@sites)
  end

end

app/views/duplicates/index.html.erb
<div class="container my-5">

  <h1>Sites</h1>

  <table class="responsive nowrap table table-hover align-middle">
    <thead>
      <tr>
        <th>Name</th>
        <th>Country</th>
        <th>Coordinates</th>
        <th class="text-end">Radiocarbon dates</th>
        <th class="text-end">Typological dates</th>
        <% if can? :manage, Site %><th><!-- Actions --></th><% end %>
      </tr>
    </thead>

    <tbody>
      <% @sites.each do |site| %>
        <tr>
          <td><%= link_to site.name, site %></td>
          <td><%= render "sites/country", site: site %></td>
          <td class="font-monospace"><%= site.coordinates.present? ? site.coordinates : na_value %></td>
          <td class="text-end"><%= site.c14s.count %></td>
          <td class="text-end"><%= site.typos.count %></td>
          <% if can? :manage, Site %><td class="text-end"><%= render 'shared/action_buttons_compact', i: site %></td><% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%== pagy_bootstrap_nav(@pagy) %>

  <% if can? :create, Site %>
    <%= link_to 'New site', new_site_path, class: 'btn btn-secondary' %>
  <% end %>
</div>