config/routes.rb
Rails.application.routes.draw do
  get 'about/acknowledgements', to: 'static_pages#acknowledgements'
  use_doorkeeper

  # Static pages
  root to: "pages#home"
  get '/home' => 'pages#home'
  get '/database' => 'pages#database'
  get '/api' => 'pages#api'

  # Articles (news posts and other pseudo-static pages)
  get '/news', to: 'articles#index', section: 'news'
  get 'news/:slug', to: 'articles#show'
  get 'about/:slug', to: 'articles#show'
  get 'docs/:slug', to: 'articles#show'

  # Redirects for backwards compatibility
  get '/about', to: redirect('/about/xronos')

  # Primary data resources
  resources :c14s do
    get 'search', on: :collection
    member do
      get 'calibrate'
      get 'calibrate_multi'
      get 'calibrate_sum'
    end
  end
  resources :c14_labs
  resources :contexts
  resources :duplicates
  resources :materials do
    get 'search', on: :collection
  end
  resources :measurement_states
  resources :references do
    get 'search', on: :collection
  end
  resources :sites do
    get 'search', on: :collection
    resources :site_names, except: [:index, :show]
  end
  resources :site_types do
    get 'search', on: :collection
  end
  resources :typos do
    get 'search', on: :collection
  end

  # Secondary data resources (no independent show/index views)
  resources :taxons, except: [:index, :show] do
    get 'search', on: :collection
  end
  resources :taxon_usages, only: :show

  # External data resources
  resources :lod_links, except: :index

  # User management
  devise_for :users, controllers: {
      registrations: 'registrations',
      sessions: 'users/sessions'
    }
  resources :user_profiles, except: [:index, :show] do
    resource :photo, only: [ :destroy ], controller: "user_profiles/photo"
  end
  resources :contributors, controller: :user_profiles, only: [ :show ]

  # Admin interface
  get "/admin" => "admin#index"
  namespace :admin do
    resources :articles, except: :show
    resources :users
  end

  # Data browser
  get 'data/index'
  post 'data/index'
  get "/data" => "xronos_data#index"

  # Search
  get "search" => "searches#index"

  # Data filter controls
  get '/resetfilter', to: 'xronos_data#reset_filter_session_variable'
  get '/turn_off_lasso', to: 'xronos_data#turn_off_lasso'
  get '/reset_manual_table_selection', to: 'xronos_data#reset_manual_table_selection'

  # Curation backend
  get "/curate" => "curate#index"
  namespace :curate do
    resources :import_tables do
      get 'edit' => 'import_tables#edit_read_options'
      get 'edit/read_options' => 'import_tables#edit_read_options'
      get 'edit/mapping' => 'import_tables#edit_mapping'
    end
    get "recent_changes" => "recent_changes#index"
  end

  # Data issues
  namespace :issues do 
    resources :c14s, only: :index do
      collection do
        get ":issue", action: :index,
          constraints: lambda { |req| C14.issues.include?(req.params[:issue].to_sym) }
      end
    end
    resources :references, only: :index do
      collection do
        get ":issue", action: :index,
          constraints: lambda { |req| Reference.issues.include?(req.params[:issue].to_sym) }
      end
    end
    resources :samples, only: :index do
      collection do
        get ":issue", action: :index,
          constraints: lambda { |req| Sample.issues.include?(req.params[:issue].to_sym) }
      end
    end
    resources :sites, only: :index do
      collection do
        get ":issue", action: :index,
          constraints: lambda { |req| Site.issues.include?(req.params[:issue].to_sym) }
      end
    end
    resources :taxons, only: :index do
      collection do
        get ":issue", action: :index,
          constraints: lambda { |req| Taxon.issues.include?(req.params[:issue].to_sym) }
      end
    end
  end
  
  # LODs
  namespace :lods do
    resources :sites, only: :index do
      collection do
        get ":lod", action: :index,
          constraints: lambda { |req| Site.lods.include?(req.params[:lod].to_sym) }
      end
    end
  end

  # API
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :data, controller: 'xronos_data'
    end
  end
  
end

app/models/reference.rb
# == Schema Information
#
# Table name: references
#
#  id         :bigint           not null, primary key
#  bibtex     :text
#  short_ref  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_references_on_short_ref  (short_ref)
#
class Reference < ApplicationRecord
  DELIM_PATTERN = '[;,]'
  MAX_SHORT_REF_LENGTH = 30

  has_many :citations, dependent: :destroy

  has_many :sites, :through => :citations, :source => :citing, :source_type => 'Site'
  has_many :c14s, :through => :citations, :source => :citing, :source_type => 'C14'
  has_many :typos, :through => :citations, :source => :citing, :source_type => 'Typo'
  has_many :dendros, :through => :citations, :source => :citing, :source_type => 'Dendro'


  validates :short_ref, presence: true

  include Versioned
  acts_as_copy_target # enable CSV exports

  include HasIssues
  @issues = [ :mixed_reference, :missing_bibtex, :long_label ]

  include PgSearch::Model
  pg_search_scope :search, 
    against: [ :short_ref, :bibtex ],
    using: { tsearch: { prefix: true } } # match partial words
  multisearchable against: [ :short_ref, :bibtex ]

  scope :with_citations_count, -> {
    select <<~SQL
      "references".*,
      (
        SELECT COUNT(citations.id) 
        FROM citations
        WHERE reference_id = "references".id
      ) AS citations_count
    SQL
  }

  def self.label
    "Bibliographic reference"
  end

  def self.icon
    "icons/reference.svg"
  end

  def really_short_ref
    if short_ref.length <= MAX_SHORT_REF_LENGTH
      return short_ref
    else
      trunc = MAX_SHORT_REF_LENGTH - 4
      return short_ref[0...trunc] + "..."
    end
  end

  def anchor
    if short_ref.blank?
      return ""
    end

    "ref-" + CGI.escape(short_ref)
  end

  def format_bibtex
    parse.to_s
  end

  def format_yaml
    parse.to_yaml
  end

  def format_json
    parse.to_json
  end

  def render
    return "No bibliographic information available." if parse.blank?

    cp = CiteProc::Processor.new style: 'apa', format: 'html', locale: 'en'
    cp.import parse.to_citeproc

    html = parse['@entry, @meta_content'].map do |e|
      cp.render :bibliography, id: e.key
    end
    html.join.html_safe
  end

  def render_citation
    return short_ref if parse.blank?

    cp = CiteProc::Processor.new style: 'chicago-author-date', format: 'html', locale: 'en'
    cp.import parse.to_citeproc

    html = parse['@entry, @meta_content'].map do |e|
      cp.render :citation, id: e.key
    end
    html.join.delete('()').html_safe
  end

  # Issues
  scope :mixed_reference, -> { where("short_ref ~* ?", DELIM_PATTERN) }
  def mixed_reference?
    short_ref.match?(DELIM_PATTERN)
  end
  
  scope :missing_bibtex, -> { where(bibtex: nil) }
  def missing_bibtex?
    bibtex.blank?
  end

  scope :long_label, -> { where("LENGTH(short_ref) > ?", MAX_SHORT_REF_LENGTH) }
  def long_label?
    return false if short_ref.blank?
    short_ref.length > MAX_SHORT_REF_LENGTH
  end

  private

  def parse
    if bibtex.present?
      BibTeX.parse bibtex, filter: :latex
    else
      bib = BibTeX::Entry.new
      bib.type = :misc
      bib.key = short_ref
      return bib
    end
  end

end

app/controllers/issues/references_controller.rb
class Issues::ReferencesController < IssuesController
  load_and_authorize_resource

  # GET /issues/references/:issue
  def index
    if issue_param.present?
      @references = Reference.send(issue_param)
    else
      @references = Reference.all
    end

    if params.has_key?(:search)
      @references = @references.search params[:search]
    end

    if params.has_key?(:references_order_by)
      order = { params[:references_order_by] => params.fetch(:references_order, "asc") }
    else
      order = :id
    end
    @references = @references.reorder(order)

    @references = @references.with_citations_count

    respond_to do |format|
      format.html { @pagy, @references = pagy(@references) }
    end
  end

  private

  def issues
    Reference.issues
  end

end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  include Tabulatable
  include Pagy::Backend

  load_and_authorize_resource

  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  # GET /references
  # GET /references.json
  # GET /references.csv
  def index
    @references = Reference.with_citations_count

    # filter
    unless reference_params.blank?
      @references = @references.where(reference_params)
    end

    # order
    if params.has_key?(:references_order_by)
      order = { params[:references_order_by] => params.fetch(:references_order, "asc") }
      @references = @references.reorder(order)
    end

    respond_to do |format|
      format.html { 
        @pagy, @references = pagy(@references)
      }
      format.json
      format.csv {
        @references = @references.select(index_csv_template)
        render csv: @references
      }
    end
  end

  # GET /c14s/search
  # GET /c14s/search.json
  def search
    @references = Reference.with_citations_count.search(params[:q])

    # order
    if params.has_key?(:references_order_by)
      order = { params[:references_order_by] => params.fetch(:references_order, "asc") }
      @references = @references.reorder(order)
    end

    respond_to do |format|
      format.html { 
        @pagy, @references = pagy(@references)
        render :index
      }
      format.json  {
        render :index
      }
    end
  end

  # GET /references/1
  # GET /references/1.json
  def show
    # @reference is already set by load_and_authorize_resource + set_reference

    @citations_count = @reference.citations.count

    @sites = @reference.sites.distinct
    @pagy_sites, @sites = pagy(@sites, page_param: :sites_page)

    @c14s = @reference.c14s.includes([:references, sample: [:material, :taxon, context: [:site]]])
    @pagy_c14s, @c14s = pagy(@c14s, page_param: :c14s_page)

    @typos = @reference.typos.includes([:references, sample: [context: [:site]]])
    @pagy_typos, @typos = pagy(@typos, page_param: :typos_page)
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(reference_params)

    respond_to do |format|
      if @reference.save
        format.html { redirect_back(fallback_location: @reference, notice: "Reference '#{@reference.short_ref}' was created.") }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_back(fallback_location: @reference, notice: "Reference '#{@reference.short_ref}' was updated.") }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    deleted_name = @reference.short_ref
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: "Reference '#{deleted_name}' was deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.fetch(:reference, {}).permit(:short_ref, :bibtex, :revision_comment)
    end
end

app/helpers/references_helper.rb
module ReferencesHelper
  include DataTableHelper
end

app/views/references/_bibliography.html.erb
<% if references.blank? %>

  <p>There are no bibliographic references attached to this record.</p>

<% else %>

  <ul class="nav nav-tabs justify-content-end" id="bibliographyTabs" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="biblio-text-tab" data-bs-toggle="tab" data-bs-target="#biblio-text" type="button" role="tab" aria-controls="biblio-text" aria-selected="true">Text</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="biblio-bibtex-tab" data-bs-toggle="tab" data-bs-target="#biblio-bibtex" type="button" role="tab" aria-controls="biblio-bibtex" aria-selected="false">BibTeX</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="biblio-json-tab" data-bs-toggle="tab" data-bs-target="#biblio-json" type="button" role="tab" aria-controls="biblio-json" aria-selected="false">JSON</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="biblio-yaml-tab" data-bs-toggle="tab" data-bs-target="#biblio-yaml" type="button" role="tab" aria-controls="biblio-yaml" aria-selected="false">YAML</button>
    </li>
  </ul>

  <div class="tab-content" id="bibliographyTabsContent">

    <div class="tab-pane fade show active p-3 border border-top-0" id="biblio-text" role="tabpanel" aria-labelledby="biblio-text-tab" tabindex="-1">
      <ul class="list-unstyled mb-0">
        <% for ref in references %>
          <li id="<%= ref.anchor %>">
            <%= ref.render %>
            <small><%= link_to "[#{ref.short_ref}]", ref %></small>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="tab-pane fade p-3 border border-top-0" id="biblio-bibtex" role="tabpanel" aria-labelledby="biblio-bibtex-tab" tabindex="0">
      <pre class="mb-0"><code class="p-0"><% for ref in references %><%= ref.format_bibtex %><% end %></code></pre>
    </div>

    <div class="tab-pane fade p-3 border border-top-0" id="biblio-json" role="tabpanel" aria-labelledby="biblio-json-tab" tabindex="0">
      <pre class="mb-0"><code class="p-0"><% for ref in references %><%= ref.format_json %><% end %></code></pre>
    </div>

    <div class="tab-pane fade p-3 border border-top-0" id="biblio-yaml" role="tabpanel" aria-labelledby="biblio-yaml-tab" tabindex="0">
      <pre class="mb-0"><code class="p-0"><% for ref in references %><%= ref.format_yaml %><% end %></code></pre>
    </div>

  </div>

<% end %>

app/views/references/_citations.html.erb
<% if references.blank? %>
  <%= na_value %>
<% else %>
    <% for ref in references do %>
      <a href="#<%= ref.anchor %>"><%= ref.render_citation %></a>
    <% end %>
<% end %>

app/views/references/_fields.html.erb
<%= f.text_field :short_ref %>
<%= f.text_area :bibtex %>

app/views/references/_form.html.erb
<%= bootstrap_form_with(model: @reference, local: true, id: "referenceForm") do |f| %>

  <%= render 'fields', f: f %>

  <h3 class="h5">Preview</h3>
  <p class="ms-3"><%= @reference.render %></p>

  <%= content_for :buttons do %>
    <%= button_tag "Cancel", type: 'reset', class: 'btn btn-danger', form: "referenceForm", data: { "bs-dismiss": "modal" } %>
    <%= button_tag "Save", class: 'btn btn-success', form: "referenceForm" %>
  <% end %>

<% end %>

app/views/references/_reference.html.erb
<article class="card">

  <div class="card-header">
    <%= xr_icon Reference, {}, { class: "img-fluid", style: "width: auto; height: 1.1rem;" } %>
    <%= Reference.label.humanize %>
  </div>

  <div class="card-body">
    <h1 class="card-title h4">
      <%= link_to reference.really_short_ref, reference %>
    </h1>

    <% unless reference.bibtex.blank? %>
      <p class="card-text text-sm">
        <small><%= reference.render %></small>
      </p>
    <% end %>
  </div>

  <div class="card-footer">
    <%= link_to reference_path(reference, anchor: "reference-citations"), 
      class: "card-link fw-semibold",
      title: Citation.label.humanize.pluralize do %>
      <%= xr_icon Citation, {}, { style: "width: auto; height: 1.1rem;" } %>
      <%= reference.citations.count %>
    <% end %>
  </div>

</article>

app/views/references/edit.html.erb
<%= render "shared/remote_modal", title: "Edit reference" do %>
  <%= render "form" %>
<% end %>

app/views/references/index.html.erb
<% content_for :title, Reference.label.humanize.pluralize %>
<% content_for :meta_description do %>List of bibliographic references associated with archaeological sites, radiocarbon dates, and other chronometric information in the XRONOS repository.<% end %>

<div class="container my-5">

  <h1>References</h1>
  <p>Showing <%= @pagy.count %> <%= Reference.label.pluralize(@pagy.count) %>.</p>

  <turbo-frame id="references-table">
    <div id="references-toolbar" class="d-flex">
      <div class="ms-auto">
        <%= link_to bs_icon("download"), references_path(format: :csv, **request.query_parameters), class: "btn btn-sm btn-outline-primary", title: "Download CSV" %>
      </div>
    </div>
    <table class="responsive nowrap table table-hover align-middle">
      <thead>
        <tr>
          <th scope="col">
            <%= link_to_order_by "Label", :short_ref %>
            <% if ordered_by?(:short_ref) %>
              <span class="text-muted"><%= order_indicator %></span>
            <% end %>
          </th>
          <th scope="col">Reference</th>
          <th scope="col">
            <%= link_to_order_by "Citations", :citations_count %>
            <% if ordered_by?(:citations_count) %>
              <span class="text-muted"><%= order_indicator %></span>
            <% end %>
          </th>
          <% if can? :manage, Reference %><th><!--Actions--></th><% end %>
        </tr>
      </thead>

      <tbody>
        <% @references.each do |reference| %>
          <tr>
            <td><%= link_to reference.short_ref, reference, target: :_top %></td>
            <td><%= reference.render %></td>
            <td><%= reference.citations_count %></td>
            <% if can? :manage, Reference %><td class="text-end"><%= render 'shared/action_buttons_compact', i: reference %></td><% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%== pagy_bootstrap_nav(@pagy) %>
  </turbo-frame>

  <% if can? :create, Reference %>
    <%= link_to 'New reference', new_reference_path, class: 'btn btn-secondary',
      data: { "turbo_frame": "remote_modal" } %>
  <% end %>
</div>

app/views/references/new.html.erb
<%= render "shared/remote_modal", title: "New reference" do %>
  <%= render "form" %>
<% end %>

app/views/references/show.html.erb
<% content_for :title, "#{@reference.render_citation}, #{Reference.label.downcase}" %>
<% content_for :meta_description,
   "#{@reference.render_citation} is cited by #{@citations_count} records of archaeological sites, radiocarbon dates, and/or other chronometric determinations in the XRONOS repository." %>

<header id="reference-header" class="bg-light text-primary">
  <div class="container my-5">
    <h1 class="display-1"><%= @reference.render_citation %></h1>
    <h2 class="display-6">
      <%= xr_icon Reference, {}, style: "height: 2.5rem;" %>
      <%= Reference.label.humanize %>
    </h2>
  </div>
</header>

<section id="reference-details" class="bg-body">
  <div class="container my-5">
    <%= render "bibliography", references: [@reference] %>
  </div>
</section>

<section id="reference-citations" class="bg-body">
  <div class="container my-5">
    <h2>Citing records</h2>
    <% c = @citations_count %>
    <p>There <%= c > 1 ? 'are' : 'is' %> <%= c %> <%= 'record'.pluralize(c) %>
        in XRONOS that <%= c > 1 ? 'cite' : 'cites' %> this reference.</p>

    <% if @sites.present? %>
      <div class="my-5">
        <h3>
          <%= xr_icon Site, {}, style: "height: 1.75rem; vertical-align: top;" %>
          <%= Site.label.humanize.pluralize %>
          <small class="text-muted">(<%= @pagy_sites.count %>)</small>
        </h3>
        <turbo-frame id="reference-sites-table">
          <ul>
            <% @sites.each do |site| %>
              <li><%= link_to site.name, site %>, <%= render "sites/country", site: site %></li>
            <% end %>
          </ul>
          <% unless @pagy_sites.pages <= 1 %>
            <%== pagy_bootstrap_nav(@pagy_sites) %>
          <% end %>
        </turbo-frame>
      </div>
    <% end %>

    <% if @c14s.present? %>
      <div class="my-5">
        <h3>
          <%= xr_icon C14, {}, style: "height: 1.75rem; vertical-align: top;" %>
          <%= C14.label.humanize.pluralize %>
          <small class="text-muted">(<%= @pagy_c14s.count %>)</small>
        </h3>
				<turbo-frame id="reference-c14s-table">
				  <% cache [@reference, :c14s, @pagy_c14s.page] do %>
					    <%= render "c14s/table", c14s: @c14s %>
				  <% end %>
				  <% unless @pagy_c14s.pages <= 1 %>
					  <%== pagy_bootstrap_nav(@pagy_c14s) %>
					<% end %>
			  </turbo-frame>
      </div>
    <% end %>

    <% if @typos.present? %>
      <div class="my-5">
        <h3>
          <%= xr_icon Typo, {}, style: "height: 1.75rem; vertical-align: top;" %>
          <%= Typo.label.humanize.pluralize %>
          <small class="text-muted">(<%= @pagy_typos.count %>)</small>
        </h3>
        <turbo-frame id="reference-typos-table">
          <%= render "typos/table", typos: @typos %>
          <% unless @pagy_typos.pages <= 1 %>
            <%== pagy_bootstrap_nav(@pagy_typos) %>
          <% end %>
        </turbo-frame>
      </div>
    <% end %>
  </div>
</section>

<section id="xronos-metadata" class="bg-light">
  <div class="container my-5">
    <h2>Metadata</h2>
    <%= render "shared/record_metadata", record: @reference, record_label: "reference" %>
  </div>

  <div class="container my-5">
    <h2>Changelog</h2>
    <%= render "application/paper_trail/versions", item: @reference %>
  </div>
</section>